kind: pipeline
type: docker
name: StormPipeline

steps:
- name: HQ
  image: starlight2834/ci_docker:latest
  environment:
    BOT_API_KEY:
      from_secret: BOT_API_KEY
    CHAT_ID:
      from_secret: CHAT_ID
    GCC:
      from_secret: GCC
    VER_CLANG:
      from_secret: VER_CLANG
    GITHUB_CREDENTIAL:
      from_secret: GITHUB_CREDENTIAL
    GITHUB_USER:
      from_secret: GIT_USER
  commands:
  - "bash build.sh"
